query Search($input: TransactionSearchInput!) {
  search {
    transactions(input: $input) {
      edges {
        node {
          id
        }
      }
      pageInfo {
        startCursor
        endCursor
      }
    }
  }
}
